language: node_js

jobs:
  include:
  - stage: Create Core PR
    script:
    - sh ./scripts/create-core-pr.sh
    env: NAME="Create CORE PR"
    if: branch = master OR branch = test

  - stage: Create Core PR 2
    script:
    - sh ./scripts/create-core-pr.sh
    env: NAME="Create CORE PR"
